apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ajithvnr2001/gitops-microservice.git'
    targetRevision: main
    path: manifests/base
  destination:
    server: 'https://kubernetes.default.svc' # This means "deploy to the cluster Argo is running in"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true